language: python

dist: xenial
install: pip install --upgrade pip tox virtualenv

matrix:
    include:
        - python: 3.7
          env: TOXENV=flake8
        - python: 3.7
          env:
            - TOXENV=bench-py37
            - TEST_FORM_MIB_SIZE=512
        - python: pypy3.6-7.1.1
          env:
            - TOXENV=bench-pypy36
            - TEST_FORM_MIB_SIZE=512

script: tox
