language: python

dist: bionic
install: pip install --upgrade pip tox

matrix:
    include:
        - python: 3.7
          env: TOXENV=flake8
        - python: 3.7
          env:
            - TOXENV=bench
            - TEST_FORM_GIB_SIZE=2

script: tox
